### ISSUE TITLE
Bot asked me to look at its logs but I have no access

### ISSUE THREAD

**Issue by pllim** [scientific-python/MeeseeksDev#130]
Not sure if this is transient problem or something to be fixed. FYI.

https://github.com/astropy/astropy/pull/16758#issuecomment-2250405415

**Comment by Carreau** [comment]
Logs don't go that far we can only retain 48h for free, but I see a bunch of interrupted connections recently. I'll keep an eye on things.

**Comment by Carreau** [comment]
also if you have a heroku account, I can add you to the owner of the bot so you have access to the logs.

**Comment by pllim** [comment]
> owner of the bot

I am not sure if I am ready for this kind of commitment. 😅 

No worries. If it happens again, I will open new issue.
