### ISSUE TITLE
Deploy for Matplotlib

### ISSUE THREAD

**Issue by Carreau** [scientific-python/MeeseeksDev#21]
This was [requested](https://mail.python.org/pipermail/matplotlib-devel/2017-September/000834.html) on the mailing list. I've already pushed commit that should handle that, the only "optimisation" we could do is pre-clone the matplotlib repository, because it can be slow to get the first time, and switch from a "git clone" to a "git fetch" , "git reset --hard origin/master" to gain some time during the backport. 

cc @choldgraf

**Comment by bsipocz** [comment]
Running on mpl atm, so closing the issue.
