### ISSUE TITLE
Feature: Grab CircleCI docs

### ISSUE THREAD

**Issue by choldgraf** [scientific-python/MeeseeksDev#33]
The scikit-learn devs use a nifty chrome extension to create a link to the documentation for a project built with CircleCI. Perhaps this is something that meeseeks could handle.

Circle exposes a list of artifacts with this API:

https://circleci.com/api/v1.1/project/github/:org/:project/:build/artifacts

e.g. this gets a list of artifacts from the latest build on the team-compass repo:

https://circleci.com/api/v1.1/project/github/jupyterhub/team-compass/latest/artifacts

returns something like:

```
[ {
  "path" : "html/.buildinfo",
  "pretty_path" : "html/.buildinfo",
  "node_index" : 0,
  "url" : "https://11-113493831-gh.circle-artifacts.com/0/html/.buildinfo"
}, {
  "path" : "html/index.html",
  "pretty_path" : "html/index.html",
  "node_index" : 0,
  "url" : "https://11-113493831-gh.circle-artifacts.com/0/html/index.html"
},
...
```
The result is a list of JSON w/ the name/path for each artifact.

Perhaps meeseeks could have a command like

```
@MeeseeksDev get-circle-artifact /path/to/artifact
```

Meeseeks would:

1. Use the org/repo from the current PR page
2. Figure out the build number for the PR (somehow)
3. Ask for the list of artifacts for this build
4. Look for the artifact that matches this file path
5. Post a comment with a link to the artifact

WDYT?

**Comment by bsipocz** [comment]
https://github.com/scientific-python/circleci-artifacts-redirector-action does this, so I'm closing this old issue. If I'm mistaken and you wanted some different functionality, please feel free to reopen.
