### ISSUE TITLE
Use "co-authored-by" for the original commit authors

### ISSUE THREAD

**Issue by jorisvandenbossche** [scientific-python/MeeseeksDev#35]
When backporting a PR, it would be nice to acknowledge the original PR author as co-author of the backported commit (eg in pandas, we use the git log automatically to generate a contributors list for a certain release). 
I think this could be done by adding "Co-authored-by: ..." to the commit message  (https://help.github.com/articles/creating-a-commit-with-multiple-authors/)

**Comment by bsipocz** [comment]
As I see recent backports, the Author is now set to the original author, and MeeseeksDev[bot] as the committer.
