### ISSUE TITLE
Unable to backport after renaming master to main

### ISSUE THREAD

**Issue by jni** [scientific-python/MeeseeksDev#47]
See e.g. https://github.com/scikit-image/scikit-image/pull/5243#issuecomment-809031809

I must admit I don't know how to look at the relevant logs. 😂

**Comment by bsipocz** [comment]
While renaming default branches may still be a problem, I would suggest to close this as the master--main migrations happened, and the bot is very unlikely to cause any more troubles.

**Comment by bsipocz** [comment]
I believe this has been addressed.
